/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Value } from './value';

export class ActionFieldDto {
    /**
    * The unique identifiers of the addon field.
    */
    'id': string;
    /**
    * A label for the certain addon field.
    */
    'label': string;
    'value': Value;
    /**
    * The type of the addon field.
    */
    'type': ActionFieldDto.TypeEnum;
    /**
    * Indicates if a field is required or not
    */
    'required': boolean;
    /**
    * Indicates if the field is disabled.
    */
    'disabled': boolean = false;
    /**
    * Indicates if the field will be hidden.
    */
    'hidden'?: boolean = false;
    /**
    * A string representing a regular expression for validation.
    */
    'regexValidation': string;
    /**
    * Indicates if the field needs remote validation.
    */
    'remoteValidation': boolean;
    /**
    * A string that represents an error message.
    */
    'error'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Value"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActionFieldDto.TypeEnum"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean"
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean"
        },
        {
            "name": "regexValidation",
            "baseName": "regexValidation",
            "type": "string"
        },
        {
            "name": "remoteValidation",
            "baseName": "remoteValidation",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActionFieldDto.attributeTypeMap;
    }
}

export namespace ActionFieldDto {
    export enum TypeEnum {
        TextBox = <any> 'TEXT_BOX',
        TextArea = <any> 'TEXT_AREA',
        Select = <any> 'SELECT',
        MultiSelect = <any> 'MULTI_SELECT',
        Description = <any> 'DESCRIPTION',
        RadioBox = <any> 'RADIO_BOX',
        Checkbox = <any> 'CHECKBOX',
        Slider = <any> 'SLIDER'
    }
}
