/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DomainAvailabilityWebsocketsDto {
    /**
    * The unique identifier of the WebSocket channel for domain availability updates.
    */
    'channelId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DomainAvailabilityWebsocketsDto.attributeTypeMap;
    }
}

