/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatParameterDataDto } from './catParameterDataDto';
import { ChallengeParametersDataDto } from './challengeParametersDataDto';
import { ClaimsTokenDataDto } from './claimsTokenDataDto';
import { DonutsPriceCategoryDataDto } from './donutsPriceCategoryDataDto';
import { IntendedUseParamsDataDto } from './intendedUseParamsDataDto';
import { PremiumPriceCategoryDataDto } from './premiumPriceCategoryDataDto';
import { ProxyServiceDataDto } from './proxyServiceDataDto';
import { SunriseDataDto } from './sunriseDataDto';
import { UKDirectDataDto } from './uKDirectDataDto';
import { XXXMemberDataDto } from './xXXMemberDataDto';

export class DomainAdditionalDto {
    /**
    * Additional parameters for Cat domains.cat is the sponsored generic top-level domain (TLD) for the Catalan language. It isn\'t territorial, however, so anyone in the world can register a . cat domain name—the only requirement is that you belong to the linguistic community for Catalan speakers.
    */
    'catParameterData'?: CatParameterDataDto;
    /**
    * Parameters for domain challenges.
    */
    'challengeParametersData'?: ChallengeParametersDataDto;
    /**
    * Data for trademark claims token.
    */
    'claimsTokenData'?: ClaimsTokenDataDto;
    /**
    * Additional parameters for Donuts premium domains.
    */
    'donutsPriceCategoryData'?: DonutsPriceCategoryDataDto;
    /**
    * Intended use parameters for domain registration.
    */
    'intendedUseParamsData'?: IntendedUseParamsDataDto;
    /**
    * If set to true and if the Proxy service is supported, the domain will have the Proxy service enabled when registered
    */
    'proxyServiceData'?: ProxyServiceDataDto;
    /**
    * This is only required for domains that the registry specify have a premium price category associated with,Premium domain names are high-quality domains that have been previously registered but are available for sale at today\'s market value. A domain is considered to be high quality if the name is shorter, regularly searched, closely associated to the actual service or industry, and typically uses a TLD
    */
    'premiumPriceCategory'?: PremiumPriceCategoryDataDto;
    /**
    * The SunriseData parameter must be supplied when sending the RegisterDomain command with a LaunchPhase of SR. A Sunrise Phase refers to a period during which, the trademark holders can register domain names corresponding to their marks before names are accessible to the general public.
    */
    'sunriseData'?: SunriseDataDto;
    /**
    * Additional data for .xxx domain names.
    */
    'xxxMemberData'?: XXXMemberDataDto;
    /**
    * Additional data for .uk direct domains.
    */
    'ukDirectData'?: UKDirectDataDto;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "catParameterData",
            "baseName": "catParameterData",
            "type": "CatParameterDataDto"
        },
        {
            "name": "challengeParametersData",
            "baseName": "challengeParametersData",
            "type": "ChallengeParametersDataDto"
        },
        {
            "name": "claimsTokenData",
            "baseName": "claimsTokenData",
            "type": "ClaimsTokenDataDto"
        },
        {
            "name": "donutsPriceCategoryData",
            "baseName": "donutsPriceCategoryData",
            "type": "DonutsPriceCategoryDataDto"
        },
        {
            "name": "intendedUseParamsData",
            "baseName": "intendedUseParamsData",
            "type": "IntendedUseParamsDataDto"
        },
        {
            "name": "proxyServiceData",
            "baseName": "proxyServiceData",
            "type": "ProxyServiceDataDto"
        },
        {
            "name": "premiumPriceCategory",
            "baseName": "premiumPriceCategory",
            "type": "PremiumPriceCategoryDataDto"
        },
        {
            "name": "sunriseData",
            "baseName": "sunriseData",
            "type": "SunriseDataDto"
        },
        {
            "name": "xxxMemberData",
            "baseName": "xxxMemberData",
            "type": "XXXMemberDataDto"
        },
        {
            "name": "ukDirectData",
            "baseName": "ukDirectData",
            "type": "UKDirectDataDto"
        }    ];

    static getAttributeTypeMap() {
        return DomainAdditionalDto.attributeTypeMap;
    }
}

