/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProductAffiliateDto {
    /**
    * An array of selected durations for the product affiliate.
    */
    'durations': Array<ProductAffiliateDto.DurationsEnum>;
    /**
    * The numeric value for the product affiliate.
    */
    'percentOrAmount': number;
    /**
    * The type of the product affiliate.
    */
    'type': ProductAffiliateDto.TypeEnum;
    /**
    * The type of action to be performed.
    */
    'action': ProductAffiliateDto.ActionEnum = ProductAffiliateDto.ActionEnum.ItemCreate;
    /**
    * The number of days after which commission should be released to the affiliate.
    */
    'releaseCommisionAfterDays': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "durations",
            "baseName": "durations",
            "type": "Array<ProductAffiliateDto.DurationsEnum>"
        },
        {
            "name": "percentOrAmount",
            "baseName": "percentOrAmount",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductAffiliateDto.TypeEnum"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "ProductAffiliateDto.ActionEnum"
        },
        {
            "name": "releaseCommisionAfterDays",
            "baseName": "releaseCommisionAfterDays",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProductAffiliateDto.attributeTypeMap;
    }
}

export namespace ProductAffiliateDto {
    export enum DurationsEnum {
        _1 = <any> '1',
        _2 = <any> '2',
        _3 = <any> '3',
        _4 = <any> '4',
        _5 = <any> '5',
        _6 = <any> '6',
        _7 = <any> '7',
        _8 = <any> '8',
        _9 = <any> '9',
        _10 = <any> '10',
        _11 = <any> '11',
        _12 = <any> '12',
        _24 = <any> '24',
        _36 = <any> '36',
        _48 = <any> '48',
        _60 = <any> '60',
        _72 = <any> '72',
        _84 = <any> '84',
        _96 = <any> '96',
        _108 = <any> '108',
        _120 = <any> '120'
    }
    export enum TypeEnum {
        Fixed = <any> 'fixed',
        Percentage = <any> 'percentage'
    }
    export enum ActionEnum {
        ItemCreate = <any> 'item/create',
        ItemSuspend = <any> 'item/suspend',
        ItemUnsuspend = <any> 'item/unsuspend',
        ItemRenew = <any> 'item/renew',
        ItemCancel = <any> 'item/cancel',
        ItemDelete = <any> 'item/delete',
        ItemUpgrade = <any> 'item/upgrade',
        ItemUpdate = <any> 'item/update',
        ItemDowngrade = <any> 'item/downgrade',
        DomainCreate = <any> 'domain/create',
        DomainLock = <any> 'domain/lock',
        DomainUnlock = <any> 'domain/unlock',
        DomainRenew = <any> 'domain/renew',
        DomainBundleAdd = <any> 'domain/bundle/add',
        DomainBundleRemove = <any> 'domain/bundle/remove',
        DomainInfo = <any> 'domain/info',
        DomainRecall = <any> 'domain/recall',
        DomainTransferCheck = <any> 'domain/transfer/check',
        DomainTransferCancel = <any> 'domain/transfer/cancel',
        DomainTransferAccept = <any> 'domain/transfer/accept',
        DomainSendAuthCode = <any> 'domain/send-auth-code',
        DomainCheckAvailability = <any> 'domain/check-availability',
        DomainShieldActivate = <any> 'domain/shield/activate',
        DomainShieldDeactivate = <any> 'domain/shield/deactivate',
        DomainDelete = <any> 'domain/delete',
        DomainContactsInfo = <any> 'domain/contacts/info',
        DomainContactsCreate = <any> 'domain/contacts/create',
        DomainContactsUpdate = <any> 'domain/contacts/update',
        DomainContactsDelete = <any> 'domain/contacts/delete',
        DomainContactsRegistrant = <any> 'domain/contacts/registrant',
        DomainContactsAdmin = <any> 'domain/contacts/admin',
        DomainContactsTech = <any> 'domain/contacts/tech',
        DomainContactsBilling = <any> 'domain/contacts/billing',
        DomainResendVerificationEmail = <any> 'domain/resend-verification-email',
        DomainCheckClaims = <any> 'domain/check-claims',
        DomainModifyHosts = <any> 'domain/modify-hosts',
        DomainModifyAuthcode = <any> 'domain/modify-authcode',
        DomainGetTransferStatus = <any> 'domain/get-transfer-status',
        DomainCancelTransfer = <any> 'domain/cancel-transfer',
        DomainRequestTransferAway = <any> 'domain/request-transfer-away',
        DomainRequestTransfer = <any> 'domain/request-transfer',
        DomainCompleteTransferAway = <any> 'domain/complete-transfer-away',
        DomainRejectTransferAway = <any> 'domain/reject-transfer-away',
        DomainRejectTransferExpired = <any> 'domain/reject-transfer-expired'
    }
}
