/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SunriseDataDto {
    /**
    * A Signed Mark Data (SMD) file is a token demonstrating that minimum eligibility requirements for Sunrise have been verified by the Clearinghouse. The SMD can be used by the Trademark holder to apply for a Domain Name during the sunrise period.
    */
    'smdFile': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "smdFile",
            "baseName": "smdFile",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SunriseDataDto.attributeTypeMap;
    }
}

