/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Attachment } from './attachment';
import { EmailPayloadDto } from './emailPayloadDto';
import { PushPayloadDto } from './pushPayloadDto';
import { SmsPayloadDto } from './smsPayloadDto';

/**
* An array tha cantains necessary data for the templates.
*/
export class TemplateData {
    /**
    * The content of the push message
    */
    'body': string;
    /**
    * The subject of the email
    */
    'subject': string;
    /**
    * An array of attachments
    */
    'attachments'?: Array<Attachment>;
    /**
    * The title of the push message
    */
    'title': string;
    /**
    * The subtitle of the push message
    */
    'subtitle'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<Attachment>"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "subtitle",
            "baseName": "subtitle",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TemplateData.attributeTypeMap;
    }
}

