/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultilangTextDto } from './multilangTextDto';
import { PricePolicyDto } from './pricePolicyDto';

export class AddonOptionsDto {
    /**
    * The unique identifier of the option
    */
    'id'?: string;
    /**
    * An array of the addon option title in all supported languages.
    */
    'title': Array<MultilangTextDto>;
    /**
    * An array that holds all the price policies applied to the addon option.
    */
    'pricePolicies': Array<PricePolicyDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "Array<MultilangTextDto>"
        },
        {
            "name": "pricePolicies",
            "baseName": "pricePolicies",
            "type": "Array<PricePolicyDto>"
        }    ];

    static getAttributeTypeMap() {
        return AddonOptionsDto.attributeTypeMap;
    }
}

