/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EsAdditionalDataDto {
    /**
    * - 0: Generic ID (a number than is not a Spanish DNI-NIF or NIE, eg passports foreign ID documents, company numbers) - 1: Spanish national personal ID/ company VAT numbers (DNI-NIF) (DNIs and NIFs can be recognized as they are comprised of an alphabetic control character plus a chain of eight numeric characters) - 3: Spanish resident alien ID Number (NIE) 
    */
    'identificationType': number;
    /**
    * The personal or corporate ID number of the contact. If the IdentificationType is 1 (DNI-NFI) or 3 (NIE), then this field will be validated to ensure the format is correct.
    */
    'identificationNumber': EsAdditionalDataDto.IdentificationNumberEnum;
    /**
    *  These entities are grouped into two types:  - Contacts type \'natural person\': Contacts registered to natural persons or individuals, that is, real persons capable of assuming rights and liabilities, capable of signing documents.  - Contacts type \'juridical person\': Contacts registered to organizations or juridical persons, that is, collective entities that may assume rights and liabilities, though in a limited fashion, such companies, associations, governmental agencies and organizations, etc.  For Contacts type \'natural person\' this field must be set to 1.  For ContactsValue type \'juridical person\' this field must be set to one of the following values:  value - Legal Entity Type * 39 - Economic Interest Grouping * 47 - Association * 59 - Sports Association * 68 - Trade Association * 124 - Savings Bank * 150 - Community Property * 152 - Condominium * 164 - Religious Order or Institution * 181 - Consulate * 197 - Public Law Association * 203 - Embassy * 229 - Municipality * 269 - Sports Federation * 286 - Foundation * 365 - Mutual Insurance Company * 434 - Provincial Government Body * 436 - National Government Body * 439 - Political Party * 476 - Trade Union * 510 - Farm Partnership * 524 - Public Limited Company / Corporation * 525 - Sports Public Limited Company * 554 - Partnership * 560 - General Partnership * 562 - Limited Partnership * 566 - Cooperative * 608 - Worker-owned Company * 612 - Limited Liability Company * 713 - Spanish (company) Branch * 717 - Temporary Consortium / Joint Venture * 744 - Worker-owned Limited Company * 745 - Provincial Government Entity * 746 - National Government Entity * 747 - Local Government Entity * 877 - Others * 878 - Designation of Origin Regulatory Council 
    */
    'contactType': EsAdditionalDataDto.ContactTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "identificationType",
            "baseName": "identificationType",
            "type": "number"
        },
        {
            "name": "identificationNumber",
            "baseName": "identificationNumber",
            "type": "EsAdditionalDataDto.IdentificationNumberEnum"
        },
        {
            "name": "contactType",
            "baseName": "contactType",
            "type": "EsAdditionalDataDto.ContactTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return EsAdditionalDataDto.attributeTypeMap;
    }
}

export namespace EsAdditionalDataDto {
    export enum IdentificationNumberEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1,
        NUMBER_3 = <any> 3
    }
    export enum ContactTypeEnum {
        NUMBER_1 = <any> 1,
        NUMBER_39 = <any> 39,
        NUMBER_47 = <any> 47,
        NUMBER_59 = <any> 59,
        NUMBER_68 = <any> 68,
        NUMBER_124 = <any> 124,
        NUMBER_150 = <any> 150,
        NUMBER_152 = <any> 152,
        NUMBER_164 = <any> 164,
        NUMBER_181 = <any> 181,
        NUMBER_197 = <any> 197,
        NUMBER_203 = <any> 203,
        NUMBER_229 = <any> 229,
        NUMBER_269 = <any> 269,
        NUMBER_286 = <any> 286,
        NUMBER_365 = <any> 365,
        NUMBER_434 = <any> 434,
        NUMBER_436 = <any> 436,
        NUMBER_439 = <any> 439,
        NUMBER_476 = <any> 476,
        NUMBER_510 = <any> 510,
        NUMBER_524 = <any> 524,
        NUMBER_525 = <any> 525,
        NUMBER_554 = <any> 554,
        NUMBER_560 = <any> 560,
        NUMBER_562 = <any> 562,
        NUMBER_566 = <any> 566,
        NUMBER_508 = <any> 508,
        NUMBER_612 = <any> 612,
        NUMBER_713 = <any> 713,
        NUMBER_717 = <any> 717,
        NUMBER_744 = <any> 744,
        NUMBER_745 = <any> 745,
        NUMBER_746 = <any> 746,
        NUMBER_747 = <any> 747,
        NUMBER_877 = <any> 877,
        NUMBER_878 = <any> 878,
        NUMBER_879 = <any> 879
    }
}
