/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ItemAffiliateDto {
    /**
    * The identifier of the user supplies affiliate.
    */
    'affiliateId': string;
    /**
    * The type of affiliate,
    */
    'affiliateType': ItemAffiliateDto.AffiliateTypeEnum;
    /**
    * The percent or amount.
    */
    'percentOrAmount': number;
    /**
    * Indicates if the item has been paid or not.
    */
    'paid': boolean;
    /**
    * The date and time when the payment was made.
    */
    'paidAt': Date;
    /**
    * The monetary value to be paid.
    */
    'value': number;
    'status': ItemAffiliateDto.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "affiliateId",
            "baseName": "affiliateId",
            "type": "string"
        },
        {
            "name": "affiliateType",
            "baseName": "affiliateType",
            "type": "ItemAffiliateDto.AffiliateTypeEnum"
        },
        {
            "name": "percentOrAmount",
            "baseName": "percentOrAmount",
            "type": "number"
        },
        {
            "name": "paid",
            "baseName": "paid",
            "type": "boolean"
        },
        {
            "name": "paidAt",
            "baseName": "paidAt",
            "type": "Date"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ItemAffiliateDto.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ItemAffiliateDto.attributeTypeMap;
    }
}

export namespace ItemAffiliateDto {
    export enum AffiliateTypeEnum {
        Fixed = <any> 'fixed',
        Percentage = <any> 'percentage'
    }
    export enum StatusEnum {
        Pending = <any> 'pending',
        Accepted = <any> 'accepted',
        Rejected = <any> 'rejected'
    }
}
