/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A read-only object of the PolicyDto.
*/
export class PolicyData {
    /**
    * The unique identifier of the policy.
    */
    'id'?: string;
    /**
    * The title of the price policy.
    */
    'title': string;
    /**
    * A description of the price policy.
    */
    'description'?: string;
    /**
    * Indicates whether this is the default price policy.
    */
    '_default': boolean;
    /**
    * The date when the policy was created.
    */
    'createdAt'?: Date;
    /**
    * The date when the policy was last updated.
    */
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PolicyData.attributeTypeMap;
    }
}

