/**
 * Hoster API
 * Hosting automation. The easy way
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AcceptedNotificationMethods } from './acceptedNotificationMethods';
import { Currency } from './currency';
import { CustomAddonPricePolicies } from './customAddonPricePolicies';
import { CustomAffiliates } from './customAffiliates';
import { CustomPricePolicies } from './customPricePolicies';
import { DefaultInvoiceContact } from './defaultInvoiceContact';
import { PaymentSubscriptionDto } from './paymentSubscriptionDto';
import { PersistentCart } from './persistentCart';
import { Settings } from './settings';

export class UserDto {
    /**
    * A unique identifier for the user.
    */
    'id'?: string;
    /**
    * An email address connected to the user.
    */
    'email'?: string;
    /**
    * Saves the user\'s default language.
    */
    'defaultLanguage'?: UserDto.DefaultLanguageEnum;
    /**
    * Indicate if a user has locked payments.
    */
    'lockedPayments'?: boolean;
    /**
    * Indicates if a user is banned.
    */
    'banned'?: boolean;
    /**
    * Three letter code about the currency this user use.
    */
    'currencyThreeLetterCode'?: string;
    /**
    * A unique identifier that indicates the parent company user belongs.
    */
    'parentCompanyId'?: string;
    'ownInvoiceContact'?: DefaultInvoiceContact;
    /**
    * A unique identifier that indicates the policy applied to this user.
    */
    'policyId'?: string;
    'customPricePolicies'?: CustomPricePolicies;
    'customAddonPricePolicies'?: CustomAddonPricePolicies;
    'customAffiliates'?: CustomAffiliates;
    /**
    * An array containing comments related to the user.
    */
    'comments'?: Array<string>;
    'currency'?: Currency;
    /**
    * Indicates invoice frequency.
    */
    'invoiceInterval'?: UserDto.InvoiceIntervalEnum;
    'acceptedNotificationMethods': AcceptedNotificationMethods;
    'persistentCart'?: PersistentCart;
    /**
    * User tags - only parent can see this
    */
    'tags'?: string;
    /**
    * User logs - only parent can see this
    */
    'logs'?: string;
    'settings': Settings;
    /**
    * Additional emails to send notifications
    */
    'additionalNotificationEmails'?: string;
    /**
    * Indicates the credit balance.
    */
    'creditBalance'?: number;
    /**
    * Indicates user account balance
    */
    'balance'?: number = 0;
    /**
    * An array of payment subscriptions associated with the user.
    */
    'paymentSubscriptions'?: Array<PaymentSubscriptionDto>;
    /**
    * The date the user was created.
    */
    'createdAt'?: Date;
    /**
    * The date the user was last updated.
    */
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "defaultLanguage",
            "baseName": "defaultLanguage",
            "type": "UserDto.DefaultLanguageEnum"
        },
        {
            "name": "lockedPayments",
            "baseName": "lockedPayments",
            "type": "boolean"
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "boolean"
        },
        {
            "name": "currencyThreeLetterCode",
            "baseName": "currencyThreeLetterCode",
            "type": "string"
        },
        {
            "name": "parentCompanyId",
            "baseName": "parentCompanyId",
            "type": "string"
        },
        {
            "name": "ownInvoiceContact",
            "baseName": "ownInvoiceContact",
            "type": "DefaultInvoiceContact"
        },
        {
            "name": "policyId",
            "baseName": "policyId",
            "type": "string"
        },
        {
            "name": "customPricePolicies",
            "baseName": "customPricePolicies",
            "type": "CustomPricePolicies"
        },
        {
            "name": "customAddonPricePolicies",
            "baseName": "customAddonPricePolicies",
            "type": "CustomAddonPricePolicies"
        },
        {
            "name": "customAffiliates",
            "baseName": "customAffiliates",
            "type": "CustomAffiliates"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<string>"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency"
        },
        {
            "name": "invoiceInterval",
            "baseName": "invoiceInterval",
            "type": "UserDto.InvoiceIntervalEnum"
        },
        {
            "name": "acceptedNotificationMethods",
            "baseName": "acceptedNotificationMethods",
            "type": "AcceptedNotificationMethods"
        },
        {
            "name": "persistentCart",
            "baseName": "persistentCart",
            "type": "PersistentCart"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string"
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "Settings"
        },
        {
            "name": "additionalNotificationEmails",
            "baseName": "additionalNotificationEmails",
            "type": "string"
        },
        {
            "name": "creditBalance",
            "baseName": "creditBalance",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "paymentSubscriptions",
            "baseName": "paymentSubscriptions",
            "type": "Array<PaymentSubscriptionDto>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return UserDto.attributeTypeMap;
    }
}

export namespace UserDto {
    export enum DefaultLanguageEnum {
        Aa = <any> 'aa',
        Af = <any> 'af',
        Ak = <any> 'ak',
        Sq = <any> 'sq',
        Am = <any> 'am',
        Ar = <any> 'ar',
        An = <any> 'an',
        Hy = <any> 'hy',
        As = <any> 'as',
        Av = <any> 'av',
        Ae = <any> 'ae',
        Ay = <any> 'ay',
        Az = <any> 'az',
        Bm = <any> 'bm',
        Ba = <any> 'ba',
        Eu = <any> 'eu',
        Be = <any> 'be',
        Bn = <any> 'bn',
        Bh = <any> 'bh',
        Bi = <any> 'bi',
        Bs = <any> 'bs',
        Br = <any> 'br',
        Bg = <any> 'bg',
        My = <any> 'my',
        Ca = <any> 'ca',
        Ch = <any> 'ch',
        Ce = <any> 'ce',
        Ny = <any> 'ny',
        Zh = <any> 'zh',
        Cv = <any> 'cv',
        Kw = <any> 'kw',
        Co = <any> 'co',
        Cr = <any> 'cr',
        Hr = <any> 'hr',
        Cs = <any> 'cs',
        Da = <any> 'da',
        Dv = <any> 'dv',
        Nl = <any> 'nl',
        Dz = <any> 'dz',
        En = <any> 'en',
        Eo = <any> 'eo',
        Et = <any> 'et',
        Ee = <any> 'ee',
        Fo = <any> 'fo',
        Fj = <any> 'fj',
        Fi = <any> 'fi',
        Fr = <any> 'fr',
        Ff = <any> 'ff',
        Gl = <any> 'gl',
        Ka = <any> 'ka',
        De = <any> 'de',
        El = <any> 'el',
        Gn = <any> 'gn',
        Gu = <any> 'gu',
        Ht = <any> 'ht',
        Ha = <any> 'ha',
        He = <any> 'he',
        Hz = <any> 'hz',
        Hi = <any> 'hi',
        Ho = <any> 'ho',
        Hu = <any> 'hu',
        Ia = <any> 'ia',
        Id = <any> 'id',
        Ie = <any> 'ie',
        Ga = <any> 'ga',
        Ig = <any> 'ig',
        Ik = <any> 'ik',
        Io = <any> 'io',
        Is = <any> 'is',
        It = <any> 'it',
        Iu = <any> 'iu',
        Ja = <any> 'ja',
        Jv = <any> 'jv',
        Kl = <any> 'kl',
        Kn = <any> 'kn',
        Kr = <any> 'kr',
        Ks = <any> 'ks',
        Kk = <any> 'kk',
        Km = <any> 'km',
        Ki = <any> 'ki',
        Rw = <any> 'rw',
        Ky = <any> 'ky',
        Kv = <any> 'kv',
        Kg = <any> 'kg',
        Ko = <any> 'ko',
        Ku = <any> 'ku',
        Kj = <any> 'kj',
        La = <any> 'la',
        Lb = <any> 'lb',
        Lg = <any> 'lg',
        Li = <any> 'li',
        Ln = <any> 'ln',
        Lo = <any> 'lo',
        Lt = <any> 'lt',
        Lu = <any> 'lu',
        Lv = <any> 'lv',
        Gv = <any> 'gv',
        Mk = <any> 'mk',
        Mg = <any> 'mg',
        Ms = <any> 'ms',
        Ml = <any> 'ml',
        Mt = <any> 'mt',
        Mi = <any> 'mi',
        Mr = <any> 'mr',
        Mh = <any> 'mh',
        Mn = <any> 'mn',
        Na = <any> 'na',
        Nv = <any> 'nv',
        Nd = <any> 'nd',
        Ne = <any> 'ne',
        Ng = <any> 'ng',
        Nb = <any> 'nb',
        Nn = <any> 'nn',
        No = <any> 'no',
        Ii = <any> 'ii',
        Nr = <any> 'nr',
        Oc = <any> 'oc',
        Oj = <any> 'oj',
        Cu = <any> 'cu',
        Om = <any> 'om',
        Or = <any> 'or',
        Os = <any> 'os',
        Pa = <any> 'pa',
        Pi = <any> 'pi',
        Fa = <any> 'fa',
        Pl = <any> 'pl',
        Ps = <any> 'ps',
        Pt = <any> 'pt',
        Qu = <any> 'qu',
        Rm = <any> 'rm',
        Rn = <any> 'rn',
        Ro = <any> 'ro',
        Rh = <any> 'rh',
        Ru = <any> 'ru',
        Sa = <any> 'sa',
        Sc = <any> 'sc',
        Sd = <any> 'sd',
        Se = <any> 'se',
        Sm = <any> 'sm',
        Sg = <any> 'sg',
        Sr = <any> 'sr',
        Gd = <any> 'gd',
        Sn = <any> 'sn',
        Si = <any> 'si',
        Sk = <any> 'sk',
        Sl = <any> 'sl',
        So = <any> 'so',
        St = <any> 'st',
        Es = <any> 'es',
        Su = <any> 'su',
        Sw = <any> 'sw',
        Ss = <any> 'ss',
        Sv = <any> 'sv',
        Ta = <any> 'ta',
        Te = <any> 'te',
        Tg = <any> 'tg',
        Th = <any> 'th',
        Ti = <any> 'ti',
        Bo = <any> 'bo',
        Tk = <any> 'tk',
        Tl = <any> 'tl',
        Tn = <any> 'tn',
        To = <any> 'to',
        Tr = <any> 'tr',
        Ts = <any> 'ts',
        Tt = <any> 'tt',
        Tw = <any> 'tw',
        Ty = <any> 'ty',
        Ug = <any> 'ug',
        Uk = <any> 'uk',
        Ur = <any> 'ur',
        Uz = <any> 'uz',
        Ve = <any> 've',
        Vi = <any> 'vi',
        Vo = <any> 'vo',
        Wa = <any> 'wa',
        Cy = <any> 'cy',
        Wo = <any> 'wo',
        Fy = <any> 'fy',
        Xh = <any> 'xh',
        Yi = <any> 'yi',
        Yo = <any> 'yo',
        Za = <any> 'za',
        Zu = <any> 'zu',
        Ab = <any> 'ab',
        Aa2 = <any> 'aa',
        Af2 = <any> 'af',
        Ak2 = <any> 'ak',
        Sq2 = <any> 'sq',
        Am2 = <any> 'am',
        Ar2 = <any> 'ar',
        An2 = <any> 'an',
        Hy2 = <any> 'hy',
        As2 = <any> 'as',
        Av2 = <any> 'av',
        Ae2 = <any> 'ae',
        Ay2 = <any> 'ay',
        Az2 = <any> 'az',
        Bm2 = <any> 'bm',
        Ba2 = <any> 'ba',
        Eu2 = <any> 'eu',
        Be2 = <any> 'be',
        Bn2 = <any> 'bn',
        Bh2 = <any> 'bh',
        Bi2 = <any> 'bi',
        Bs2 = <any> 'bs',
        Br2 = <any> 'br',
        Bg2 = <any> 'bg',
        My2 = <any> 'my',
        Ca2 = <any> 'ca',
        Ch2 = <any> 'ch',
        Ce2 = <any> 'ce',
        Ny2 = <any> 'ny',
        Zh2 = <any> 'zh',
        Cv2 = <any> 'cv',
        Kw2 = <any> 'kw',
        Co2 = <any> 'co',
        Cr2 = <any> 'cr',
        Hr2 = <any> 'hr',
        Cs2 = <any> 'cs',
        Da2 = <any> 'da',
        Dv2 = <any> 'dv',
        Nl2 = <any> 'nl',
        Dz2 = <any> 'dz',
        En2 = <any> 'en',
        Eo2 = <any> 'eo',
        Et2 = <any> 'et',
        Ee2 = <any> 'ee',
        Fo2 = <any> 'fo',
        Fj2 = <any> 'fj',
        Fi2 = <any> 'fi',
        Fr2 = <any> 'fr',
        Ff2 = <any> 'ff',
        Gl2 = <any> 'gl',
        Ka2 = <any> 'ka',
        De2 = <any> 'de',
        El2 = <any> 'el',
        Gn2 = <any> 'gn',
        Gu2 = <any> 'gu',
        Ht2 = <any> 'ht',
        Ha2 = <any> 'ha',
        He2 = <any> 'he',
        Hz2 = <any> 'hz',
        Hi2 = <any> 'hi',
        Ho2 = <any> 'ho',
        Hu2 = <any> 'hu',
        Ia2 = <any> 'ia',
        Id2 = <any> 'id',
        Ie2 = <any> 'ie',
        Ga2 = <any> 'ga',
        Ig2 = <any> 'ig',
        Ik2 = <any> 'ik',
        Io2 = <any> 'io',
        Is2 = <any> 'is',
        It2 = <any> 'it',
        Iu2 = <any> 'iu',
        Ja2 = <any> 'ja',
        Jv2 = <any> 'jv',
        Kl2 = <any> 'kl',
        Kn2 = <any> 'kn',
        Kr2 = <any> 'kr',
        Ks2 = <any> 'ks',
        Kk2 = <any> 'kk',
        Km2 = <any> 'km',
        Ki2 = <any> 'ki',
        Rw2 = <any> 'rw',
        Ky2 = <any> 'ky',
        Kv2 = <any> 'kv',
        Kg2 = <any> 'kg',
        Ko2 = <any> 'ko',
        Ku2 = <any> 'ku',
        Kj2 = <any> 'kj',
        La2 = <any> 'la',
        Lb2 = <any> 'lb',
        Lg2 = <any> 'lg',
        Li2 = <any> 'li',
        Ln2 = <any> 'ln',
        Lo2 = <any> 'lo',
        Lt2 = <any> 'lt',
        Lu2 = <any> 'lu',
        Lv2 = <any> 'lv',
        Gv2 = <any> 'gv',
        Mk2 = <any> 'mk',
        Mg2 = <any> 'mg',
        Ms2 = <any> 'ms',
        Ml2 = <any> 'ml',
        Mt2 = <any> 'mt',
        Mi2 = <any> 'mi',
        Mr2 = <any> 'mr',
        Mh2 = <any> 'mh',
        Mn2 = <any> 'mn',
        Na2 = <any> 'na',
        Nv2 = <any> 'nv',
        Nd2 = <any> 'nd',
        Ne2 = <any> 'ne',
        Ng2 = <any> 'ng',
        Nb2 = <any> 'nb',
        Ii2 = <any> 'ii',
        Nr2 = <any> 'nr',
        Oc2 = <any> 'oc',
        Oj2 = <any> 'oj',
        Cu2 = <any> 'cu',
        Om2 = <any> 'om',
        Or2 = <any> 'or',
        Os2 = <any> 'os',
        Pa2 = <any> 'pa',
        Pi2 = <any> 'pi',
        Fa2 = <any> 'fa',
        Pl2 = <any> 'pl',
        Ps2 = <any> 'ps',
        Pt2 = <any> 'pt',
        Qu2 = <any> 'qu',
        Rm2 = <any> 'rm',
        Rn2 = <any> 'rn',
        Ro2 = <any> 'ro',
        Rh2 = <any> 'rh',
        Ru2 = <any> 'ru',
        Sa2 = <any> 'sa',
        Sc2 = <any> 'sc',
        Sd2 = <any> 'sd',
        Se2 = <any> 'se',
        Sm2 = <any> 'sm',
        Sg2 = <any> 'sg',
        Sr2 = <any> 'sr',
        Gd2 = <any> 'gd',
        Sn2 = <any> 'sn',
        Si2 = <any> 'si',
        Sk2 = <any> 'sk',
        Sl2 = <any> 'sl',
        So2 = <any> 'so',
        St2 = <any> 'st',
        Es2 = <any> 'es',
        Su2 = <any> 'su',
        Sw2 = <any> 'sw',
        Ss2 = <any> 'ss',
        Sv2 = <any> 'sv',
        Ta2 = <any> 'ta',
        Te2 = <any> 'te',
        Tg2 = <any> 'tg',
        Th2 = <any> 'th',
        Ti2 = <any> 'ti',
        Bo2 = <any> 'bo',
        Tk2 = <any> 'tk',
        Tl2 = <any> 'tl',
        Tn2 = <any> 'tn',
        To2 = <any> 'to',
        Tr2 = <any> 'tr',
        Ts2 = <any> 'ts',
        Tt2 = <any> 'tt',
        Tw2 = <any> 'tw',
        Ty2 = <any> 'ty',
        Ug2 = <any> 'ug',
        Uk2 = <any> 'uk',
        Ur2 = <any> 'ur',
        Uz2 = <any> 'uz',
        Ve2 = <any> 've',
        Vi2 = <any> 'vi',
        Vo2 = <any> 'vo',
        Wa2 = <any> 'wa',
        Cy2 = <any> 'cy',
        Wo2 = <any> 'wo',
        Fy2 = <any> 'fy',
        Xh2 = <any> 'xh',
        Yi2 = <any> 'yi',
        Yo2 = <any> 'yo',
        Za2 = <any> 'za',
        Zu2 = <any> 'zu'
    }
    export enum InvoiceIntervalEnum {
        Instant = <any> 'instant',
        Weekly = <any> 'weekly',
        Monthly = <any> 'monthly',
        PerRequest = <any> 'per request'
    }
}
